In [20]:
import numpy as np

# ndarray
nd = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(nd)

nd1 = nd + 1
print(nd1)

print(nd.sum(), nd1.sum())

nd2 = nd > nd1
print(nd2)

nd2 = nd < nd1
print(nd2)

nd2 = nd < nd1
print(nd2, nd2.sum())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
45 54
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]] 9
